package com.happiest.minds.ffms.sales.pojo;

// Generated Jun 13, 2016 4:36:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActivityVo generated by hbm2java
 */
public class ActivityVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String activityName;
	private String activityCode;
	private Long addedBy;
	private Date addedOn;
	private Long modifiedBy;
	private Date modifiedOn;
	private Integer status;
	private String completionPercentage;
	private String remarks;
	private Integer ticketType;

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getActivityName() {
		return activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public String getActivityCode() {
		return activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public Long getAddedBy() {
		return addedBy;
	}

	public void setAddedBy(Long addedBy) {
		this.addedBy = addedBy;
	}

	public Date getAddedOn() {
		return addedOn;
	}

	public void setAddedOn(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Long getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedOn() {
		return modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCompletionPercentage() {
		return completionPercentage;
	}

	public void setCompletionPercentage(String completionPercentage) {
		this.completionPercentage = completionPercentage;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getTicketType() {
		return ticketType;
	}

	public void setTicketType(Integer ticketType) {
		this.ticketType = ticketType;
	}

	@Override
	public String toString() {
		return "ActivityVo{" +
				"id=" + id +
				", activityName='" + activityName + '\'' +
				", activityCode='" + activityCode + '\'' +
				", addedBy=" + addedBy +
				", addedOn=" + addedOn +
				", modifiedBy=" + modifiedBy +
				", modifiedOn=" + modifiedOn +
				", status=" + status +
				", completionPercentage='" + completionPercentage + '\'' +
				", remarks='" + remarks + '\'' +
				", ticketType=" + ticketType +
				'}';
	}
}
